name: Propose Version Bump

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump type (patch, minor, or major)'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  create-bump-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Get new version (dry-run)'
        id: get_new_version
        uses: callowayproject/bump-my-version@master
        with:
          args: ${{ inputs.bump-type }} --dry-run --allow-dirty

      - name: Set new version and branch name
        run: |
          echo "NEW_VERSION=${{ steps.get_new_version.outputs.current-version }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=bump/v${{ steps.get_new_version.outputs.current-version }}" >> $GITHUB_ENV
          echo "PREVIOUS_VERSION=${{ steps.get_new_version.outputs.previous-version }}" >> $GITHUB_ENV

      - name: Bump version files (no commit)
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "false"
          BUMPVERSION_COMMIT: "false" 
        with:
          args: ${{ inputs.bump-type }} --no-commit --no-tag

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Bump version to ${{ env.NEW_VERSION }}"
          body: |
            This PR bumps the version from ${{ env.PREVIOUS_VERSION }} to ${{ env.NEW_VERSION }}.
            
            Once merged, the commit on `main` will be tagged automatically.
          
          branch: ${{ env.BRANCH_NAME }}
          base: main
          labels: "version-bump"
