name: Propose Version Bump

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump type (patch, minor, or major)'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  create-bump-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate APP Token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          
      - name: Bump version files
        id: bump
        uses: callowayproject/bump-my-version@master
        with:
          args: ${{ inputs.bump-type }} --no-commit --no-tag

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.get_token.outputs.token }}
          author: "versioning pr bot[bot] <my-org-cla-bots@googlegroups.com>"
          committer: "versioning pr bot[bot] <my-org-cla-bots@googlegroups.com>"
          commit-message: "Bump version: ${{ steps.bump.outputs.previous-version }} â†’ ${{ steps.bump.outputs.current-version }}"
          title: "Bump version to ${{ steps.bump.outputs.current-version }}"
          body: |
            This PR bumps the version from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}.
            
            Once merged, the commit on `main` will be tagged automatically.
          branch: "bump/v${{ steps.bump.outputs.current-version }}"
          base: main
          labels: "version-bump"
